#!/bin/bash
# Auto-generated Minecraft run script for Docker
# Generated by: ./gradlew :loader-fabric:exportDockerRunScript

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_DIR="${SCRIPT_DIR}/run"

# Build classpath
CLASSPATH=""
while IFS= read -r line; do
    if [ -n "$line" ]; then
        CLASSPATH="${CLASSPATH}:${SCRIPT_DIR}/${line}"
    fi
done < "${SCRIPT_DIR}/classpath.txt"
CLASSPATH="${CLASSPATH:1}" # Remove leading colon

# JVM arguments
JVM_ARGS="${JAVA_OPTS:--Xmx4G -Xms2G}"

# Fabric uses net.fabricmc.loader.impl.launch.knot.KnotClient as main class
MAIN_CLASS="net.fabricmc.loader.impl.launch.knot.KnotClient"

echo "Starting Minecraft..."
echo "Classpath entries: $(wc -l < "${SCRIPT_DIR}/classpath.txt")"
echo "Run directory: $RUN_DIR"

mkdir -p "$RUN_DIR"
cd "$RUN_DIR"

exec java $JVM_ARGS \
    -Dfabric.gameJarPath="${SCRIPT_DIR}/libs/minecraft-merged-client.jar" \
    -Dfabric.development=false \
    -cp "$CLASSPATH" \
    "$MAIN_CLASS"
